services:
  web:
    build: .
    working_dir: /app/code/code
    command: sh -c "sleep 10 && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" 
volumes:
  postgres_data: